version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=agent_planning_db
      - POSTGRES_USER=agent_user
      - POSTGRES_PASSWORD=agent_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    command: postgres -c 'max_connections=1000'

volumes:
  postgres_data:
    driver: local