services:
  # Service de base de données PostgreSQL
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=agent_planning_db
      - POSTGRES_USER=agent_user
      - POSTGRES_PASSWORD=agent_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    command: postgres -c 'max_connections=1000'

  # Service backend Django
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DATABASE_NAME=agent_planning_db
      - DATABASE_USER=agent_user
      - DATABASE_PASSWORD=agent_password
      - DATABASE_HOST=db  # IMPORTANT: utilisez le nom du service Docker
      - DATABASE_PORT=5432

  # Service frontend React
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
    driver: local