# Generated by Django 5.2 on 2025-04-03 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddSetting',
            new_name='AdSetting',
        ),
    ]
